### ISSUE TITLE
Add a 'before' munging function

### ISSUE THREAD

**Issue by champgm** [richardschneider/express-mung#10]
I was using express-mung today and found that it was lacking something I needed. I wanted to gather timings for some calls and I ended up having to write a function to grab a begin-time and use it as normal middleware before the call. Then, I used an express-mung function to grab the begin-time from the request object and insert call time and elapsed time as an attribute of the body. 

So I was thinking, how about adding the ability to provide a function which can interact with request & response when the user calls use() and then doing the normal stuff. Basically, if a caller provides another function, call it here: https://github.com/richardschneider/express-mung/blob/af483160f9f4132be5e24ebfd23d851e2505d260/index.js#L21-L23

That way, I could refactor my code eventually to be something like:
```
app.use(mung.json(startTimer, {}, stopTimer)
```

So, is there any interest in this? I'd be willing to contribute the changes if so.

**Comment by richardschneider** [comment]
Interesting idea.  Let me investigate (prototype) and I'll get back to you.  Thanks for the suggestion.

**Comment by id0Sch** [comment]
you can use https://github.com/expressjs/response-time
i've been using it in production for a while now and it works just fine.

**Comment by champgm** [comment]
@id0Sch , I specifically needed to place the timings into the body. That's why I ended up using express-mung.

**Comment by richardschneider** [comment]
I don't think this feature should be added, because it is not about response processing.

Your refactoring

    app.use(mung.json(startTimer, {}, stopTimer))

Can also be written

    app.use(startTimer, mung.json(stopTimer))

with no changes to express-mung

**Comment by champgm** [comment]
Oh! I didn't realize you could specify many middlewares at once. Very cool, thanks!
