### ISSUE TITLE
Feature request: `mung.write` 

### ISSUE THREAD

**Issue by hedgeday** [richardschneider/express-mung#15]
I have a use case for a `mung.writeJson` function which overrides the `res.write` function only when the response type `application/json`. 

For example, [apollo-server](https://github.com/apollographql/apollo-server) sends graphQL responses via `res.write`, after setting the `Content-Type` and `Content-Length` headers. You can take a look at the specific source code [here](https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/src/expressApollo.ts#L48). If this happens, `mung.json` is never called even though the response is a json object. 

Thoughts on this? I have a simple working implementation, I have opened a pull request (#14). Let me know what you think 😄

**Comment by richardschneider** [comment]
Why not submit a PR to apollo-server to use `res.json`?

**Comment by hedgeday** [comment]
Good question. From what I can see it's a matter of consistency and possible code reusability within the repo. Apollo-server supports several server side frameworks (express, connect, hapi and so on) - it seems not to rely on framework specific functions like the express-specific `res.json`, and relies instead on the node native `res.write` function across the codebase. Given that, I'm not sure it would be the right thing to change it in this one instance.

**Comment by richardschneider** [comment]
`mung.write` added to NPM v0.5.0 release. 

Thanks for all the extra effort.

**Comment by anodynos** [comment]
I'm using it in this scenario, but after manipulating the response I'm getting: 
* a failure on Chrome `ERR_CONTENT_LENGTH_MISMATCH 200 (OK)` (after 5.1 secs) 
* an OK response on PostMan, again after 5.1 again (normal query takes 0.1 secs). 

I can indeed see the `Content-Length` header having a very different size (the manipulated is smaller) - any ideas how to go about it? Should I also manipulate the headers?

**Comment by richardschneider** [comment]
Is it possible to show the code (or point to the repo) that manipulates the the response?

**Comment by richardschneider** [comment]
@anodynos Also, could you open a new issue.
