### ISSUE TITLE
problem in frontend unit tests

### ISSUE THREAD

**Issue by ghwrivas** [richardschneider/express-mung#19]
I'm using express-mung in a common library, this for my express backend, but other functions of the library I use in the frontend. In the backend everything works correctly relating to express-mung but in the frontend an error occurs when trying to execute the unit tests:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Use of reserved word 'let' in strict mode
  at webpack:///~/express-mung/index.js:3:0 <- src/test.ts:174140
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Use of reserved word 'let' in strict mode
  at webpack:///~/express-mung/index.js:3:0 <- src/test.ts:174140
```
any suggestions?

**Comment by richardschneider** [comment]
`express-mung` only works in NodeJS, just like `express`.  It cannot be in a browser, which I assume you call a `frontend`

I would suggest that this common library does not `require` express and express-mung when being web packed for a browser.  You may also want to consider splitting the common library into a NodeJS and browser package.
