### ISSUE TITLE
When using res.json(Number) you get server error

### ISSUE THREAD

**Issue by yonatanhg** [richardschneider/express-mung#21]
When using res.json(Number) the middleware call res.send instead of res.json:
![image](https://user-images.githubusercontent.com/31180027/43565813-cfbe1688-9634-11e8-8903-80fb501dee58.png)
If the first param in res.json is number then it use this param as the status instead of the value: 
res.send(200) == res.status(200).end()
When I use res.json(Number) is it possible to use res.json instead of res.send?

**Comment by richardschneider** [comment]
Good catch.  The current version of [res.send](https://expressjs.com/en/api.html#res.send) does not allow a Number.  Older versions did allow setting of status code.  In either case, returning a Number with mung will fail.

I'm thinking the code should be changed to

    return res.send(String(json));

Would this work for you?

**Comment by richardschneider** [comment]
Fixed, see PR #22
