### ISSUE TITLE
Using express-mung to modify static folder doesn't seem to work

### ISSUE THREAD

**Issue by fernandojsg** [richardschneider/express-mung#23]
I'm quite new on express so I'm not sure if this is a no-sense, but is it possible to modify content served using `express.static`? I've tried the following code and `inspect` is never being called.

```javascript
var app = require('express')();
const mung = require('express-mung');

function inspect (json, req, res) {
  console.log('>>>>>');
  json.inspected_by = 'me'
}

app.use(mung.json(inspect));
app.use('/static', express.static('static'));

app.listen(3000, function(){
  console.log('mung listening on *:3000');
});
```

**Comment by richardschneider** [comment]
`express.static` does not return JSON; it returns a stream.  So the `mung.json` hook is never called.

You can use `mung.write` to modify a chunk of the stream.  See https://github.com/richardschneider/express-mung/blob/master/test/write.js for some examples.

**Comment by richardschneider** [comment]
See https://github.com/richardschneider/express-mung/issues/24#issuecomment-417796629
