### ISSUE TITLE
On mung.write, chrome throws ERR_CONTENT_LENGTH_MISMATCH 200 (OK) 

### ISSUE THREAD

**Issue by anodynos** [richardschneider/express-mung#25]
When using `mung.write` chrome throws an `ERR_CONTENT_LENGTH_MISMATCH 200 (OK)` if the new content is different (I guess smaller) in size (reported [here](https://github.com/richardschneider/express-mung/issues/15#issuecomment-423859610)).

The simple solution I found is to

    const changedChunk = JSON.stringify(bodyJson);
    res.set('Content-Length', changedChunk.length);

but I guess `mung.write` could do the same behind the scenes.

_BTW thanks for this library, its a life saver!_

PS: For reference the code is  
```
  expressInstance.use(
    mung.write((chunk, encoding, req, res) => {      
      if (req.graphqlLodash_transform) {
        const bodyJson = JSON.parse(chunk);
        bodyJson.data = req.graphqlLodash_transform(bodyJson.data);
        const changedChunk = JSON.stringify(bodyJson);
        res.set('Content-Length', changedChunk.length);
        
        return changedChunk;
      } // else return unmodified
    }),
  );
```

**Comment by richardschneider** [comment]
Thanks for the bug report and work around!

`mung.write` cannot set the `Content-Length` because it is possible to call `res.write` multiple times. So setting the header(s) must be application logic.

I should update the documentation to mention this!

**Comment by anodynos** [comment]
Thanks for lib & immediate response!

**Comment by anodynos** [comment]
OOOR, you could set it everytime the changed chunk is returned. What problems would that create?

**Comment by richardschneider** [comment]
A header can only be set before the first `res.write`; see https://nodejs.org/api/http.html#http_response_write_chunk_encoding_callback. 

If the application is doing multiple writes for a single request, then `mung.write` does not know the `Content-Length`.
