### ISSUE TITLE
mung.onError assumes json

### ISSUE THREAD

**Issue by niftylettuce** [richardschneider/express-mung#26]
I noticed that `mung.onError` always assumes the Accept content type is application/json, and sends a `json` response.  I guess we can modify this on our own, but I was just sharing the bug find.

**Comment by richardschneider** [comment]
Thanks for the comment and you are correct. 

Note that somewhere in the HTTP spec, it states that Accept is a recommendation to the server.  The server is always free to send any response type.

Also, there is no standard on how to return an error message.  As you suggested, this is really the app's responsibility.  It should set `mung.onError` to return an app specific response.
