### ISSUE TITLE
Connecting request and response data into single object

### ISSUE THREAD

**Issue by aleksander351** [richardschneider/express-mung#27]
I would like to save api request together with the corresponding response data.

I understand that is not possible with mung at this moment. Am I correct?

What would be a possible workaround?

**Comment by richardschneider** [comment]
@aleksander351 I think that [mung.jsonAsync](https://github.com/richardschneider/express-mung#mungjsonasyncfn-options) will work for you. It gives you the request and JSON response.  You can can then save it.

**Comment by aleksander351** [comment]
Ok, so for example:

     `
      app.use(mung.jsonAsync(
        function (json, req, res) {
            console.log(json);
        }
      ));
     `
I get the response: `"message": "Cannot read property 'then' of undefined"`

Please provide a simple example of an implementation.

**Comment by richardschneider** [comment]
`mung.jsonAsync` expects the function to return a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), which is what you will need if you are saving the request and response.

For your simple case, just use `mung.json`.

```js
app.use(mung.json(
    function (json, req, res) {
        console.log(json);
    }
));
```

**Comment by aleksander351** [comment]
Never mind, I figured it out from the tests code:

```
app.use(mung.jsonAsync(
    function transform(json, req, res) {
        return Promise.resolve(json)
            .then(json => {
                // execute your custom functions here
                return json;
            });            
    }
));
```
Thank you for your help. Closing the issue.
