### ISSUE TITLE
The app does not respond after added express-mung middleware

### ISSUE THREAD

**Issue by 0angelic0** [richardschneider/express-mung#3]
If I move the express-mung as last middleware the app can respond but the function 'redact' (as the name from usage example) which I want to modify the response is not called.

I used express generator to scaffold my app.

Code below the app does not respond.
```
app.use(mung);

// routes, users and api are express router
app.use('/', routes);
app.use('/users', users);
app.use('/api', api);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});

module.exports = app;
```

Code below the app can respond but function 'redact' is not called
```
// routes, users and api are express router
app.use('/', routes);
app.use('/users', users);
app.use('/api', api);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});

app.use(mung);

module.exports = app;
```

**Comment by richardschneider** [comment]
Do **not** do `app.use(mung);` It is not correct.  

`mung` is middleware for middleware.  As the [readme](https://github.com/richardschneider/express-mung) illustrates you should have your middleware, such as `redact` call `mung`.

You have not shown your `redact.js`, so I can't provide much more help.  If you post your code, or even easier just point me to the github repo, I can then provide more details.

Thanks for trying the package.

**Comment by 0angelic0** [comment]
OK, I made a github repo [here](https://github.com/0angelic0/web). You can run the app with npm start

The files in focus are app.js and nulljson.js

app.js
line 28 as [1]
line 66 as [2]

nulljson.js
line 12 as [3]

At current state of the repo [2] has been commented and the app is working fine. You can make request at:
1. http://localhost:3000/api/cinema/0001 < found data
2. http://localhost:3000/api/cinema/0003 < not found data; response is {} (modified response success)

If I comment [3] which I no longer want to modify the body
1. http://localhost:3000/api/cinema/0001 < found data
2. http://localhost:3000/api/cinema/0003 < NOT RESPONDING

Then if I comment [1] and uncomment [2] (which [3] is still commented)
1. http://localhost:3000/api/cinema/0001 < found data
2. http://localhost:3000/api/cinema/0003 < not found data; response is null, no console output 'nulljson'

Thanks

**Comment by 0angelic0** [comment]
Another little side note in your usage example

    exports = mung.json(redact);

It have to be?

    module.exports = mung.json(redact);

**Comment by richardschneider** [comment]
`exports`

**Comment by richardschneider** [comment]
The [pull request](https://github.com/0angelic0/web/pull/1) gets `express-mung` and `nulljson` working.

**Comment by richardschneider** [comment]
24 hours have passed, I assume you are happy with the solution, so I'm closing the issue.  But feel free to post a comment and I'll re-open the issue.

Good luck with your app.

**Comment by 0angelic0** [comment]
Yes, your solution works perfectly. I comment this just to comfirm that. Sorry for late checking the issue.

Thank you for your help.
