### ISSUE TITLE
OnError Issue

### ISSUE THREAD

**Issue by zeeshanalisyed** [richardschneider/express-mung#4]
Their is nothing mentioned regarding onError function how to use this, i been trying to include this as 

> app.use(mung.onError(function(err, req, res){}));

but i keep recieving this error

> TypeError: Cannot read property 'status' of undefined

Which is defined in 

> express-mung/index.js

**Comment by richardschneider** [comment]
`onError` is called whenever an exception encountered while running the `mung` code.  By default it sends a 500 response with the `error.message` as JSON payload.

You can redefine it's behaviour with a [monkey patch](https://en.wikipedia.org/wiki/Monkey_patch)

      mung.errort = function (err, req, res) {
        // do something with the error
    }

You should not use it in `app.use`.
