### ISSUE TITLE
res.status() and mung.json()

### ISSUE THREAD

**Issue by hk0i** [richardschneider/express-mung#6]
It seems like `res.status()` and `mung.json()` don't play well together.
I'm fairly new to express in general so I may be doing something wrong here, but I would have expected to be able to do something like:

```javascript
//untested pseudo-code, I can cook up a better example that
//fully illustrates the problem if necessary.
function getSomething(req, res) {
  //hack because there seems to be no way to get status from `res` in express:
  res.locals.statusCode = 404;
  //set status code to 404 and send json
  res.status(404).json({message: 'Resource not found'});
}

function addMeta(body, req, res) {
  //this function *never* gets called when calling `res.status()` as in the `getSomething()` function.
  body.statusCode = res.locals.statusCode;
}

app.use(mung.json(addMeta));
app.get('/something', getSomething);
```

Once `res.status()` is called, the addMeta method never gets called it seems.

What I'm really trying to do here is provide a way for my api to slap on extra meta data at the end of the json response with the http status code for clients that may not be able to receive non-200 http status codes. It would be great to be able to, from the `addMeta` function in my example, make a call like `res.getStatus()` and check the status code that has been set by `res.status()` in the previous middleware or route or whatever.

**Comment by richardschneider** [comment]
It's been designed to work `res.status`, see the [test](https://github.com/richardschneider/express-mung/blob/master/test/json.js#L26).

I think your problem is that `getSomething` never calls `res.end`.  The last line should be:

    res.status(404).json({message: 'Resource not found'}).end();

**Comment by hk0i** [comment]
Awesome! That worked. Is there a way to retrieve the status code on the receiving end?

I'm also now having issues now with async methods not getting "munged." I could open a separate ticket for that though if it's better, but something like this:

```javascript
        const connection = mysql.createConnection(mysqlConf);
        connection.connect();

        connection.query('SELECT 1 + 1 as result', function(err, rows, fields) {
            if (err) throw err;
            res.json(rows).end();
        });
```

is avoiding the munge as well.

**Comment by richardschneider** [comment]
On the server side, you can use [`res.statusCode`](https://nodejs.org/api/http.html#http_response_statuscode). 

This should work:

    function addMeta(body, req, res) {
        body.statusCode = res.statusCode;
    }


On the receiver side, it depends on the package you are using to call the server.

**Comment by hk0i** [comment]
`res.statusCode` only seems to be working for 200 status codes for me.
When I try

```javascript
        res.status(404).json(response).end();
```
It doesn't work

**Comment by richardschneider** [comment]
Let me write a test.  Talk to you in 20 mins.

**Comment by richardschneider** [comment]
Published [v0.4.6](https://www.npmjs.com/package/express-mung) that allows munging of error responses.

Try this:

    app.use(mung.json(addMeta, { mungError: true } ));

**Comment by hk0i** [comment]
Works like a charm. Thanks!

It's also safe to ignore that async mysql thing I was talking about before. I'm not sure what the issue was but I seem to have solved that as well.

This error munging is great because now I can check for some parameter and pass everything as http 200 if needed and append the actual status code in the JSON response. I really appreciate the effort 👍

**Comment by richardschneider** [comment]
No worries mate,  I appreciate the feed back.
